name: Build Nginx Variants RPM (RHEL9)

on:
  schedule:
    - cron: '0 4 * * 0'   # 每周日凌晨 4:00 UTC
  workflow_dispatch:
    inputs:
      target:
        description: 'Select build target'
        required: true
        type: choice
        options:
          - nginx-1.25.0
          - nginx-latest
          - tengine-latest
          - openresty-latest

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9

    # 定义环境变量（用于后续步骤引用）
    env:
      BUILD_USER: builder
      BUILD_HOME: /home/builder
      RPMBUILD: /home/builder/rpmbuild

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Builder User
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Copy Project Files
        run: |
          cd $GITHUB_WORKSPACE
          sudo chown -R builder .
          cp -r ./* /home/builder/
        # 不使用 env.BUILD_HOME，直接写死路径

      - name: Setup Build Environment
        run: |
          su - builder -c "cd /home/builder && ./build/scripts/setup_env.sh"

      - name: Parse Build Target
        run: |
          case "${{ inputs.target }}" in
            nginx-1.25.0)
              echo "BUILD_TARGET=nginx-1.25.0" >> $GITHUB_ENV
              ;;
            nginx-latest)
              echo "BUILD_TARGET=nginx-latest" >> $GITHUB_ENV
              ;;
            tengine-latest)
              echo "BUILD_TARGET=tengine-latest" >> $GITHUB_ENV
              ;;
            openresty-latest)
              echo "BUILD_TARGET=openresty-latest" >> $GITHUB_ENV
              ;;
          esac

      - name: Build RPM
        run: |
          su - builder -c "cd /home/builder && ./build/scripts/build.sh"
        env:
          BUILD_TARGET: ${{ env.BUILD_TARGET }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpms-${{ env.BUILD_TARGET }}
          path: /home/builder/rpmbuild/RPMS/x86_64/*.rpm
          if-no-files-found: warn  # 可选：避免无文件时报错
      

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rpms-${{ env.BUILD_TARGET }}
          path: /home/builder/rpmbuild/RPMS/x86_64/*.rpm

      - name: Extract Version from SPEC
        if: github.event_name == 'workflow_dispatch'
        run: |
          SPEC_FILE=$(find /home/builder/rpmbuild/SPECS -name "*.spec" | head -1)
          if [[ -f "$SPEC_FILE" ]]; then
            VERSION=$(grep "^Version:" "$SPEC_FILE" | awk '{print $2}')
            echo "RPM_VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "❌ SPEC file not found"
            exit 1
          fi

      - name: Create GitHub Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_TARGET }}-v${{ env.RPM_VERSION }}
          name: Release ${{ env.BUILD_TARGET }} ${{ env.RPM_VERSION }}
          files: /home/builder/rpmbuild/RPMS/x86_64/*.rpm
          generate_release_notes: true
